"""HTTP middleware stack: transport security and request guards.

:func:`install_middleware` wires the full stack onto the FastAPI application in
the correct order. From outermost (runs first on the way in) to innermost:

1. **Security headers** — adds ``X-Content-Type-Options: nosniff``,
   ``X-Frame-Options: DENY`` and a ``Content-Security-Policy`` with
   ``frame-ancestors 'none'`` to every response (Req 21.4). Installed
   outermost so it also covers responses produced by framework-level error
   handling.
2. **CORS** — restricts cross-origin requests to the configured allowlist
   (``settings.CORS_ALLOW_ORIGINS``) (Req 21.1).
3. **Body-size limit** — rejects requests whose body exceeds
   ``settings.MAX_BODY_SIZE_BYTES`` with HTTP 413 (Req 17.5).
4. **Auth rate limit** — a Redis-backed fixed-window limiter applied to
   ``/auth/*`` paths that returns HTTP 429 once a client exceeds
   ``settings.AUTH_RATE_LIMIT_PER_MINUTE`` requests in the current minute
   (Req 21.2).

The body-size and rate-limit guards are implemented as **pure ASGI**
middleware (wrapping ``scope``/``receive``/``send``) rather than Starlette's
``BaseHTTPMiddleware``. ``BaseHTTPMiddleware`` buffers the request body and
interferes with downstream body streaming and with FastAPI's dependency
resolution of ``Request`` parameters; the pure-ASGI form avoids that entirely
and also lets the body-size guard reject an oversized request *before* the
whole body is buffered.

Forwarded-protocol handling for ``X-Forwarded-Proto`` (Req 21.3) is provided by
Uvicorn's ``ProxyHeadersMiddleware``, installed here as well so the app honors
the forwarded scheme even outside Uvicorn (e.g. under the test client), which
lets generated redirect URLs use ``https`` when terminated at a proxy.

All error responses produced here use the shared error envelope from
``app.core.errors`` so they are consistent and secret-free.

**Redis degradation policy (documented):** the rate limiter **fails open**. If
Redis is unreachable or errors, the request is allowed through rather than
returning a 5xx. Auth correctness (OAuth ``state``, token validation) does not
depend on the limiter, so availability is preferred over rejecting legitimate
traffic during a cache outage; the failure is logged for operators.
"""

from __future__ import annotations

import logging
import math
import time
from typing import Callable

from fastapi import FastAPI, status
from starlette.datastructures import Headers
from starlette.middleware.cors import CORSMiddleware
from starlette.requests import Request
from starlette.types import ASGIApp, Message, Receive, Scope, Send

from app.config import Settings
from app.core.errors import build_error_response

logger = logging.getLogger("atomic_ai.middleware")

# Fixed rate-limit window length in seconds.
_RATE_LIMIT_WINDOW_SECONDS = 60

# Path prefix that the auth rate limiter guards.
_AUTH_PATH_PREFIX = "/auth"


# --- Security headers ---------------------------------------------------------

_SECURITY_HEADERS: tuple[tuple[bytes, bytes], ...] = (
    (b"x-content-type-options", b"nosniff"),
    (b"x-frame-options", b"DENY"),
    # Disallow framing by any origin; complements X-Frame-Options.
    (b"content-security-policy", b"frame-ancestors 'none'"),
    (b"referrer-policy", b"no-referrer"),
    (b"x-permitted-cross-domain-policies", b"none"),
)


class SecurityHeadersMiddleware:
    """Add secure-default response headers to every response (Req 21.4).

    Implemented as pure ASGI middleware (wrapping ``send``) rather than
    ``BaseHTTPMiddleware`` so the headers are applied to *every* outgoing
    response. Installed as the outermost application middleware so it also
    wraps ``send`` for responses generated by framework-level error handling
    (e.g. an unhandled exception turned into a 500). Headers already present
    (for instance when an error envelope set them explicitly) are not
    duplicated.
    """

    def __init__(self, app: ASGIApp) -> None:
        self._app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self._app(scope, receive, send)
            return

        async def send_with_headers(message: Message) -> None:
            if message["type"] == "http.response.start":
                headers = message.setdefault("headers", [])
                present = {name.lower() for name, _ in headers}
                for name, value in _SECURITY_HEADERS:
                    if name not in present:
                        headers.append((name, value))
            await send(message)

        await self._app(scope, receive, send_with_headers)


# --- Body-size limit ----------------------------------------------------------

async def _send_error_response(
    scope: Scope, receive: Receive, send: Send, response
) -> None:
    """Emit an ``app.core.errors`` JSONResponse over the raw ASGI channel."""
    await response(scope, receive, send)


class MaxBodySizeMiddleware:
    """Reject requests whose body exceeds the configured limit with 413 (Req 17.5).

    Pure-ASGI implementation. It first checks a declared ``Content-Length`` and
    rejects immediately when it exceeds the limit (so an oversized upload is
    refused before the body is read). For requests without a reliable length
    (chunked transfer), it wraps ``receive`` and counts bytes as the body
    streams in, short-circuiting with a 413 the moment the running total
    exceeds the limit — without buffering the whole body itself.
    """

    def __init__(self, app: ASGIApp, max_body_size: int) -> None:
        self._app = app
        self._max_body_size = max_body_size

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self._app(scope, receive, send)
            return

        headers = Headers(scope=scope)
        content_length = headers.get("content-length")
        if content_length is not None:
            try:
                declared = int(content_length)
            except ValueError:
                await _send_error_response(
                    scope,
                    receive,
                    send,
                    build_error_response(
                        status_code=status.HTTP_400_BAD_REQUEST,
                        message="Invalid Content-Length header.",
                    ),
                )
                return
            if declared > self._max_body_size:
                await self._reject(scope, receive, send)
                return
            # Declared length is within the limit: forward without buffering.
            await self._app(scope, receive, send)
            return

        # No Content-Length (chunked/unknown length): count bytes as the body
        # streams in and reject the moment the running total exceeds the limit.
        # We read the body here so we can refuse before invoking the app, then
        # replay the bytes we consumed via a wrapped ``receive``.
        received = 0
        replay: list[bytes] = []
        more = True
        while more:
            message = await receive()
            msg_type = message["type"]
            if msg_type == "http.disconnect":
                return
            if msg_type != "http.request":
                continue
            chunk = message.get("body", b"")
            received += len(chunk)
            if received > self._max_body_size:
                await self._reject(scope, receive, send)
                return
            replay.append(chunk)
            more = message.get("more_body", False)

        index = 0

        async def replay_receive() -> Message:
            nonlocal index
            if index < len(replay):
                chunk = replay[index]
                index += 1
                return {
                    "type": "http.request",
                    "body": chunk,
                    "more_body": index < len(replay),
                }
            return {"type": "http.request", "body": b"", "more_body": False}

        await self._app(scope, replay_receive, send)

    async def _reject(self, scope: Scope, receive: Receive, send: Send) -> None:
        await _send_error_response(
            scope,
            receive,
            send,
            build_error_response(
                status_code=status.HTTP_413_CONTENT_TOO_LARGE,
                message="The request body exceeds the maximum allowed size.",
            ),
        )


# --- Auth-endpoint rate limiting ---------------------------------------------

def _client_key_from_scope(scope: Scope) -> str:
    """Derive a per-client key for rate limiting from the ASGI scope.

    Uses the connection's client host. Because ``ProxyHeadersMiddleware`` runs
    first, the scope's client reflects the real client when deployed behind a
    trusted proxy.
    """
    client = scope.get("client")
    if client:
        return client[0]
    return "unknown"


def _rate_limit_bucket(now: float) -> int:
    """Return the fixed-window bucket index for the given time."""
    return int(now // _RATE_LIMIT_WINDOW_SECONDS)


async def check_auth_rate_limit(
    redis_client: object,
    client_id: str,
    limit: int,
    now: float | None = None,
) -> tuple[bool, int]:
    """Fixed-window rate-limit check for one client.

    Increments the counter for the client's current one-minute window and
    returns ``(allowed, retry_after_seconds)``. ``allowed`` is False once the
    count for the window strictly exceeds ``limit``.

    Fails open: if the Redis client raises, the request is allowed and
    ``(True, 0)`` is returned (see module docstring for rationale).

    The Redis client is expected to expose async ``incr`` and ``expire`` (as
    ``redis.asyncio`` does). Kept dependency-injected so it can be unit-tested
    with a fake.
    """
    current = time.time() if now is None else now
    bucket = _rate_limit_bucket(current)
    redis_key = f"ratelimit:auth:{client_id}:{bucket}"
    try:
        count = await redis_client.incr(redis_key)  # type: ignore[attr-defined]
        if count == 1:
            # First hit in this window: set the TTL so the key self-expires.
            await redis_client.expire(redis_key, _RATE_LIMIT_WINDOW_SECONDS)  # type: ignore[attr-defined]
    except Exception:  # noqa: BLE001 - limiter must not crash the request path
        logger.warning("Auth rate limiter degraded: Redis unavailable; failing open")
        return True, 0

    if count > limit:
        # Seconds until the current window rolls over.
        elapsed = current - bucket * _RATE_LIMIT_WINDOW_SECONDS
        retry_after = max(1, int(math.ceil(_RATE_LIMIT_WINDOW_SECONDS - elapsed)))
        return False, retry_after
    return True, 0


class AuthRateLimitMiddleware:
    """Rate-limit ``/auth/*`` requests per client per minute (Req 21.2).

    Pure-ASGI implementation so it never consumes or buffers the request body
    (it only inspects the path and client), leaving downstream body streaming
    and dependency resolution untouched.
    """

    def __init__(
        self,
        app: ASGIApp,
        settings: Settings,
        redis_factory: Callable[[], object] | None = None,
    ) -> None:
        self._app = app
        self._settings = settings
        self._limit = settings.AUTH_RATE_LIMIT_PER_MINUTE
        self._redis_factory = redis_factory or self._default_redis_factory
        self._redis: object | None = None

    def _default_redis_factory(self) -> object:
        import redis.asyncio as redis_asyncio

        return redis_asyncio.from_url(
            self._settings.REDIS_URL.get_secret_value(),
            socket_connect_timeout=2,
            socket_timeout=2,
        )

    def _get_redis(self) -> object | None:
        if self._redis is None:
            try:
                self._redis = self._redis_factory()
            except Exception:  # noqa: BLE001 - fail open if client can't be built
                logger.warning("Auth rate limiter: could not create Redis client; failing open")
                return None
        return self._redis

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http" or not scope.get("path", "").startswith(
            _AUTH_PATH_PREFIX
        ):
            await self._app(scope, receive, send)
            return

        redis_client = self._get_redis()
        if redis_client is None:
            await self._app(scope, receive, send)
            return

        allowed, retry_after = await check_auth_rate_limit(
            redis_client, _client_key_from_scope(scope), self._limit
        )
        if not allowed:
            response = build_error_response(
                status_code=status.HTTP_429_TOO_MANY_REQUESTS,
                message="Too many authentication requests. Please try again later.",
                headers={"Retry-After": str(retry_after)},
            )
            await response(scope, receive, send)
            return
        await self._app(scope, receive, send)


# --- Installation -------------------------------------------------------------

def install_middleware(
    app: FastAPI,
    settings: Settings,
    redis_factory: Callable[[], object] | None = None,
) -> None:
    """Install the full middleware stack on the application.

    Middleware added later runs first (Starlette wraps them outermost-last), so
    the calls below are ordered so that on an inbound request the effective
    order is: ProxyHeaders -> SecurityHeaders -> CORS -> BodySize -> RateLimit
    -> route handler.

    ``SecurityHeadersMiddleware`` is installed near the outside so its wrapped
    ``send`` observes the ``http.response.start`` of *every* response, including
    ones produced by framework-level error handling.
    """
    # Innermost first (runs last on the way in).
    app.add_middleware(
        AuthRateLimitMiddleware, settings=settings, redis_factory=redis_factory
    )
    app.add_middleware(
        MaxBodySizeMiddleware, max_body_size=settings.MAX_BODY_SIZE_BYTES
    )

    if settings.CORS_ALLOW_ORIGINS:
        app.add_middleware(
            CORSMiddleware,
            allow_origins=list(settings.CORS_ALLOW_ORIGINS),
            allow_credentials=True,
            allow_methods=["*"],
            allow_headers=["*"],
        )

    # Security headers outermost of our own guards so they wrap error responses.
    app.add_middleware(SecurityHeadersMiddleware)

    # Outermost (runs first): normalize forwarded proto/host so downstream sees
    # the real scheme (https) behind a terminating proxy (Req 21.3).
    _install_proxy_headers(app)


def _install_proxy_headers(app: FastAPI) -> None:
    """Add Uvicorn's ProxyHeadersMiddleware honoring X-Forwarded-Proto.

    Trusts all upstream hosts ("*") for the forwarded headers; in production the
    only reachable upstream is the deployment's own reverse proxy. Import is
    defensive so a missing optional dependency does not break app construction.
    """
    try:
        from uvicorn.middleware.proxy_headers import ProxyHeadersMiddleware
    except Exception:  # noqa: BLE001 - proxy header support is best-effort
        logger.warning("ProxyHeadersMiddleware unavailable; forwarded-proto not honored")
        return
    app.add_middleware(ProxyHeadersMiddleware, trusted_hosts="*")
